---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-app

    template:
      metadata:
        labels:
          app: weather-app
      spec:
        serviceAccountName: default
        securityContext:
          fsGroup: 1001
          runAsGroup: 1001
          runAsNonRoot: true
          runAsUser: 1001
        containers:
          - name: weather-app
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - all
              privileged: false
              readOnlyRootFilesystem: true
            imagePullPolicy: IfNotPresent
            image: weather-app:latest
            ports:
              - containerPort: 5000
                name: http
